### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by psprashob** [ibm-garage-tsa/cp4mcm-installer#1]
Here are our observations after running the script.
1) The script executed correctly without any errors(log in box link)
2) All common services components installed correctly
3) There are no pods in the CP4MCM namespace

$ oc get pods -n cp4m
NAME                                                 READY   STATUS             RESTARTS   AGE
ibm-management-catalog-deployment-569c88d69c-tw9tw   0/1     ImagePullBackOff   0          135m

I am sharing with you the description when I do a describe pod on the failed pod. 
[https://ibm.box.com/s/xyaznarif9qglghpu8kxoowj1zt4kmes](url)
We got this same error twice. Kindly let me know if we are missing something.

**Comment by jdiggity22** [comment]
@psprashob ... Can you give me some more information? 
What command did you run to install? 
Did you make sure to export your entitlement key? `export ENTITLED_REGISTRY_KEY="YOUR ENTITLEMENT KEY"`
Can you describe the pod for me? `oc describe po -n cp4m ibm-management-catalog-deployment-569c88d69c-tw9tw`

Thanks!

**Comment by jdiggity22** [comment]
@psprashob I didn't notice you had included the `oc describe po` in the logs. It looks to me that the key you are using is not entitled to these images. You will have to talk to your sales team to make sure you have the correct entitlements and give it another try. You can verify this by manually trying to pull the pod. I will see if I can add some code to detect this issue before the installation starts.

**Comment by psprashob** [comment]
@jdiggity22 
To make sure the entitlement key is correct, we did a one-click manual install and it worked fine. We also used the same entitlement key to pull the operator and it was also was successful. 

_docker login cp.icr.io --username cp --password <entitlement_key>
docker pull cp.icr.io/cp/cp4mcm/cp4mcm-operator-catalog@sha256:2c39ee0ca65f968cc45a00a3e32c25dd6e32910635ed3bd9baae58c9c8875ed9

$ docker pull cp.icr.io/cp/cp4mcm/cp4mcm-operator-catalog@sha256:2c39ee0ca65f968cc45a00a3e32c25dd6e32910635ed3bd9baae58c9c8875ed9
sha256:2c39ee0ca65f968cc45a00a3e32c25dd6e32910635ed3bd9baae58c9c8875ed9: Pulling from cp/cp4mcm/cp4mcm-operator-catalog
dc0665975713: Pulling fs layer
8e3c93d02cd2: Pulling fs layer
6f89338e3bca: Pulling fs layer
a731cc260ef5: Pulling fs layer
357855a869df: Pulling fs layer
643cf2f68326: Pulling fs layer
cb7bdda35259: Pulling fs layer
4f6d6b0859b3: Pulling fs layer
54059b6b6af1: Pulling fs layer
a731cc260ef5: Waiting
357855a869df: Waiting
643cf2f68326: Waiting
cb7bdda35259: Waiting
4f6d6b0859b3: Waiting
54059b6b6af1: Waiting
6f89338e3bca: Verifying Checksum
6f89338e3bca: Download complete
8e3c93d02cd2: Verifying Checksum
8e3c93d02cd2: Download complete
a731cc260ef5: Verifying Checksum
a731cc260ef5: Download complete
357855a869df: Verifying Checksum
357855a869df: Download complete
643cf2f68326: Verifying Checksum
643cf2f68326: Download complete
4f6d6b0859b3: Verifying Checksum
4f6d6b0859b3: Download complete
54059b6b6af1: Verifying Checksum
54059b6b6af1: Download complete
cb7bdda35259: Verifying Checksum
cb7bdda35259: Download complete
dc0665975713: Verifying Checksum
dc0665975713: Download complete
dc0665975713: Pull complete
8e3c93d02cd2: Pull complete
6f89338e3bca: Pull complete
a731cc260ef5: Pull complete
357855a869df: Pull complete
643cf2f68326: Pull complete
cb7bdda35259: Pull complete
4f6d6b0859b3: Pull complete
54059b6b6af1: Pull complete
Digest: sha256:2c39ee0ca65f968cc45a00a3e32c25dd6e32910635ed3bd9baae58c9c8875ed9
Status: Downloaded newer image for cp.icr.io/cp/cp4mcm/cp4mcm-operator-catalog@sha256:2c39ee0ca65f968cc45a00a3e32c25dd6e32910635ed3bd9baae58c9c8875ed9_

**Comment by jdiggity22** [comment]
@psprashob That is strange that it will let you manually pull it, but you are seeing an error in your pod logs. I wonder if the secret didn't get created or the entitlement key that was exported was incorrect. Can you very that the exported entitlement key and the entitlement key you used in your manual image pull test were exactly the same?

**Comment by psprashob** [comment]
We identified this as an issue with the entitlement key. The key that was used to manually pull images was different from the key that was embedded in the script. The environment is working fine now. Thanks a lot for your help. I am now marking this issue as closed.

**Comment by jdiggity22** [comment]
Thanks @psprashob for the update. I have created an issue to validate the entitled registry key prior to installation to detect this scenario in the future. https://github.com/ibm-garage-tsa/cp4mcm-installer/issues/5
