### ISSUE TITLE
CP4MCM sizes too small

### ISSUE THREAD

**Issue by KarenGdaniec** [ibm-garage-tsa/cp4mcm-installer#18]
We are getting customer issues coming in where the CP4MCM installation has been created using the IBM Garage scripts especially https://github.com/ibm-garage-tsa/cp4mcm-installer/blob/master/cp4m/cp4mcm-install.sh
The default size for Kafka here, 10G, is much too small.  The minimum size the CP4MCM product needs for Kafka is 25G.
The problem is, when a customer/user runs out of space on Kafka, it's difficult to fix and they are losing data the entire time that Kafka is too small, and there is no way to recover the data that has been lost.

Can garage team please update the size for Kafka in this script to 25G?

**Comment by KarenGdaniec** [comment]
@brightzheng100 @jdiggity22 can one of you please address this?  Thanks in advance.

**Comment by jdiggity22** [comment]
@KarenGdaniec Sure.. I think that is as simple change. I will update the issue what it has been merged.

**Comment by jdiggity22** [comment]
@KarenGdaniec  I updated the default to be 25GB. I hope this helps resolve the broader issue with running out of space.

**Comment by KarenGdaniec** [comment]
Thank you John!
